name: Deploy Node App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/my-first-node

            echo "Pull latest code"
            git pull origin main

            echo "Stop old container"
            docker stop my-first-node || true
            docker rm my-first-node || true

            echo "Build new image"
            docker build -t my-first-node .

            echo "Run container"
            docker run -d \
              --name my-first-node \
              --restart unless-stopped \
              -p 3000:3000 \
              my-first-node

            echo "Deployment completed"